# Generated by Django 4.2.8 on 2026-03-07 07:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResult', '0008_examresult_ending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('question_id', models.CharField(help_text='关联题目ID', max_length=255)),
                ('student_id', models.CharField(help_text='学生ID', max_length=255)),
                ('exam_result_id', models.CharField(blank=True, help_text='关联考试结果ID', max_length=255, null=True)),
                ('answer_text', models.TextField(help_text='学生答案文本')),
                ('grading_mode', models.CharField(choices=[('LENIENT', 'Lenient'), ('STRICT', 'Strict')], help_text='评分模式', max_length=20)),
                ('final_score', models.FloatField(blank=True, help_text='最终得分', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCORING', 'Scoring'), ('SCORED', 'Scored')], default='PENDING', help_text='评分状态', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'answer_record',
            },
        ),
        migrations.CreateModel(
            name='ScorePointDetail',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('answer_record_id', models.CharField(help_text='关联答题记录ID', max_length=255)),
                ('scoring_point_id', models.CharField(help_text='关联评分细则ID', max_length=255)),
                ('llm_1_hit', models.CharField(blank=True, help_text='LLM-1命中: FULL/MISS', max_length=10, null=True)),
                ('llm_1_score', models.FloatField(blank=True, help_text='LLM-1该点得分', null=True)),
                ('llm_1_reason', models.CharField(blank=True, help_text='LLM-1判定理由', max_length=500, null=True)),
                ('llm_2_hit', models.CharField(blank=True, help_text='LLM-2命中: FULL/MISS', max_length=10, null=True)),
                ('llm_2_score', models.FloatField(blank=True, help_text='LLM-2该点得分', null=True)),
                ('llm_2_reason', models.CharField(blank=True, help_text='LLM-2判定理由', max_length=500, null=True)),
                ('llm_3_hit', models.CharField(blank=True, help_text='LLM-3命中: FULL/MISS', max_length=10, null=True)),
                ('llm_3_score', models.FloatField(blank=True, help_text='LLM-3该点得分', null=True)),
                ('llm_3_reason', models.CharField(blank=True, help_text='LLM-3判定理由', max_length=500, null=True)),
                ('final_hit', models.CharField(blank=True, help_text='最终命中: FULL/MISS', max_length=10, null=True)),
                ('final_score', models.FloatField(blank=True, help_text='最终该点得分', null=True)),
                ('vote_count', models.IntegerField(blank=True, help_text='投票计数', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
            ],
            options={
                'db_table': 'score_point_detail',
            },
        ),
        migrations.AlterField(
            model_name='examresultdetail',
            name='solution',
            field=models.TextField(blank=True, help_text='学生作答结果', max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='AnswerDraft',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('exam_result_id', models.CharField(help_text='关联考试结果ID', max_length=255)),
                ('question_id', models.CharField(help_text='关联题目ID', max_length=255)),
                ('answer', models.TextField(blank=True, default='', help_text='草稿答案文本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'answer_draft',
                'unique_together': {('exam_result_id', 'question_id')},
            },
        ),
    ]
