# Generated by Django 4.2.8 on 2026-05-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionManagement', '0011_scoringpoint_questions_grading_mode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorArchive',
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(help_text='试题参考答案'),
        ),
    ]
